package main

import (
	"os"
	"sort"
	"strings"
	"unicode"
)
import "fmt"
import "mapreduce"

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// TODO: you should complete this to do the inverted index challenge
	var contents []string
	x := -1

	for i, j := range value {
		if unicode.IsLetter(j) {
			if x == -1 {
				x = i
			}
		} else {
			// If a non-letter character is found and there was a word before it,
			// extract the word and add it to the contents slice
			if x != -1 {
				contents = append(contents, value[x:i])
				x = -1
			}
		}
	}

	// If the last word extends to the end of the document, extract and add it

	if x != -1 {
		contents = append(contents, value[x:])
	}

	for _, word := range contents {
		// Append a KeyValue struct with the word as the key and document as the value

		res = append(res, mapreduce.KeyValue{Key: word, Value: document})
	}
	return res
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// TODO: you should complete this to do the inverted index challenge
	sort.Strings(values)

	//duplicates document names map.
	dupdoc := make(map[string]bool)
	var unidoc []string

	for _, doc := range values {
		if !dupdoc[doc] {
			dupdoc[doc] = true
			unidoc = append(unidoc, doc)
		}
	}
	// Join unique document names into a comma-separated string
	documentnames := strings.Join(unidoc, ",")

	// Format the output as "word: #documents documents,sorted,and,separated,by,commas,"
	result := fmt.Sprintf("%d %s", len(unidoc), documentnames)
	return result
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
